### ISSUE TITLE
Невозможно добавить категорию с одинаковым названием для разных юзеров

### ISSUE THREAD

**Issue by kirillovsky** [liders/ASKA.Note#7]
Например, я пытался добавить категорию '111'
E11000 duplicate key error collection: aska-note-development.categories index: title_1 dup key: { : "111" }
MongoError: E11000 duplicate key error collection: aska-note-development.categories index: title_1 dup key: { : "111" } at Function.MongoError.create (d:\WEB\ASKA.Note\node_modules\mongodb-core\lib\error.js:31:11) at toError (d:\WEB\ASKA.Note\node_modules\mongodb\lib\utils.js:139:22) at d:\WEB\ASKA.Note\node_modules\mongodb\lib\collection.js:659:23 at handleCallback (d:\WEB\ASKA.Note\node_modules\mongodb\lib\utils.js:120:56) at d:\WEB\ASKA.Note\node_modules\mongodb\lib\bulk\unordered.js:465:9 at handleCallback (d:\WEB\ASKA.Note\node_modules\mongodb\lib\utils.js:120:56) at resultHandler (d:\WEB\ASKA.Note\node_modules\mongodb\lib\bulk\unordered.js:413:5) at d:\WEB\ASKA.Note\node_modules\mongodb-core\lib\connection\pool.js:461:18 at _combinedTickCallback (internal/process/next_tick.js:73:7) at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by kirillovsky** [comment]
@liders, Большой Лидовский. Разберись плз

**Comment by liders** [comment]
Пофикшено.
Теперь пользователь не может добавить категорию, название которой уже есть в БД у этого же пользователя.
Но пользователи с разными ID могут добавлять категории с одинаковым названием.
